[[pages]]
path = "app/ibf.py"
name = "Peringatan Dini"
icon = "âš ï¸"

[[pages]]
path = "app/aktual.py"
name = "Aktual"
icon = "ğŸ§­"

[[pages]]
path = "app/prakiraan.py"
name = "Prakiraan Cuaca"
icon = "ğŸŒ¤ï¸"

[[pages]]
path = "app/rainrate.py"
name = "Rainrate"
icon = "ğŸŒ§ï¸"

[[pages]]
path = "app/wrhp.py"
name = "Angin dan RASON"
icon = "ğŸˆ"

[[pages]]
path = "app/regional.py"
name = "Parameter Regional"
icon = "ğŸŒ"
