show_pages(
    [
        Page("app/aktual.py", "Aktual", "ğŸ "),
        Page("app/prakiraan.py", "XML", ":books:"),
        Page("app/wrhp.py", "Angin dan RASON", "ğŸ“–"),
        Page("app/regional.py", "Parameter Regional", "âœï¸"),
        Page("app/rainrate.py", "Rainrate", "ğŸ§°"),
    ]
)

add_page_title()  # Optional method to add title and icon to current page


