[[pages]]
path = "app/aktual.py"
name = "Aktual"
icon = "ğŸ "

[[pages]]
path = "app/prakiraan.py"
name = "XML"
icon = ":books:"

[[pages]]
path = "app/wrhp.py"
name = "Angin dan RASON"
icon = "ğŸ "

[[pages]]
path = "app/regional.py"
name = "Parameter Regional"
icon = ":books:"

[[pages]]
path = "app/rainrate.py"
name = "Rainrate"
icon = "ğŸ "
